services:
  # Backend para o Site (UI pública)
  - type: web
    name: site-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: ENABLE_SQL_ENDPOINT
        value: "false"
      - key: ENABLE_GPT_WRITE
        value: "false"
      - key: READ_ONLY
        # true = somente leitura; false = habilita escrita com EDITOR_TOKEN
        value: "true"
      - key: ALLOWED_ORIGINS
        # Domínio público do frontend
        value: https://financeiro-frontend-hg4w.onrender.com
      - key: RATE_LIMIT_STORAGE_URI
        value: memory://
      - key: RATE_LIMIT_EDIT
        value: 30/minute
      - key: RATE_LIMIT_GLOBAL
        value: 300/minute
      - key: TRUST_PROXY
        value: "true"
      # Banco de dados (preencher no painel ou aqui, sem expor segredos)
      - key: DB_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.thmekudlkuwjuddkyhpi
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: "5432"
      # Se for permitir edição via site, defina EDITOR_TOKEN no painel
      - key: EDITOR_TOKEN
        sync: false

  # Backend para o Agente GPT (API programática)
  - type: web
    name: gpt-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: ENABLE_SQL_ENDPOINT
        value: "true"
      - key: ENABLE_GPT_WRITE
        value: "true"
      - key: READ_ONLY
        value: "true"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: RATE_LIMIT_STORAGE_URI
        value: memory://
      - key: RATE_LIMIT_ADMIN
        value: 10/minute
      - key: RATE_LIMIT_GPT_WRITE
        value: 20/minute
      - key: TRUST_PROXY
        value: "true"
      - key: DB_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.thmekudlkuwjuddkyhpi
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: GPT_TOKEN
        sync: false
      # (Opcional) proteger /sql com token
      - key: ADMIN_TOKEN
        sync: false

  # Frontend (Static Site) — usar web + env: static no Blueprint
  - type: web
    name: financeiro-frontend
    env: static
    buildCommand: |
      cd frontend
      npm ci --no-audit --no-fund
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        # URL pública do site-backend
        value: https://site-backend-hg4w.onrender.com
